baseurl: /MSHE-Student-Resources

collections:
  info:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "info"
    values:
      layout: "info-page"

statuses:
  - newly admitted students
  - current students
  - non-matriculated students
  - certificate students
  
list-bies:
  - category
  - action
  - student status

paginate: 50