baseurl: /MSHE-Student-Resources

collections:
  info:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "info"
    values:
      layout: "info-page"

statuses:
  - newly admitted students
  - current students
  - non-matriculated students
  - certificate students
  
list-bies:
  - category
  - action
  - student status

categories:
  - Academic Services and Programming
  - Admissions and Enrollment Management
  - Alumni Relations and Development
  - Athletics
  - Career Services
  - Civic Engagement and Volunteerism
  - Social Justice (e.g., diversity, inclusion, access, equality, equity)
  - Financial Issues
  - Higher Education Policy
  - Strategic Planning and Institutional Research
  - Student Development
  - Student Engagement
  - Student Wellness
  - Study Abroad and International Education
  
consent:
  - yes
  - no