baseurl: /MSHE_Canvas_Resources

collections:
  info:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "info"
    values:
      layout: "info-page"
      
categories: 
  - academics
  - internships