baseurl: /MSHE-Student-Resources

collections:
  info:
    output: true
  mp_content:
    output: true
  workshops:
    output: true
    
defaults:
  -
    scope:
      path: ""
      type: "info"
    values:
      layout: "info-page"
  - 
    scope:
      path: ""
      type: "mp_content"
    values:
      layout: "mp-guide-page"
  - 
    scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop-page"

statuses:
  - newly admitted students
  - current students
  - non-matriculated students
  - certificate students
  
list-bies:
  - category
  - action
  - student status
  
topics: 
  - academics
  - career resources
  - financial aid
  - internships
  - master project
  - policies
  - student life
  - technology
  - wellness
  
actions: 
  - apply for jobs
  - attend a conference
  - choose an elective
  - find a place to live
  - relax and enjoy
  - succeed in classes

categories:
  - Academic Services and Programming
  - Admissions and Enrollment Management
  - Alumni Relations and 